const Nationality = require('../models/nationalityModel');

// Function to add nationalities
exports.addNationalities = async (req, res) => {
  const nationalities = [
    {"Label": "Afghan", "Value": "Afghan"},
    {"Label": "Albanian", "Value": "Albanian"},
    {"Label": "Algerian", "Value": "Algerian"},
    {"Label": "American", "Value": "American"},
    {"Label": "Andorran", "Value": "Andorran"},
    {"Label": "Angolan", "Value": "Angolan"},
    {"Label": "Argentinian", "Value": "Argentinian"},
    {"Label": "Armenian", "Value": "Armenian"},
    {"Label": "Australian", "Value": "Australian"},
    {"Label": "Austrian", "Value": "Austrian"},
    {"Label": "Azerbaijani", "Value": "Azerbaijani"},
    {"Label": "Bahamian", "Value": "Bahamian"},
    {"Label": "Bahraini", "Value": "Bahraini"},
    {"Label": "Bangladeshi", "Value": "Bangladeshi"},
    {"Label": "Barbadian", "Value": "Barbadian"},
    {"Label": "Belarusian", "Value": "Belarusian"},
    {"Label": "Belgian", "Value": "Belgian"},
    {"Label": "Belizean", "Value": "Belizean"},
    {"Label": "Beninese", "Value": "Beninese"},
    {"Label": "Bhutanese", "Value": "Bhutanese"},
    {"Label": "Bolivian", "Value": "Bolivian"},
    {"Label": "Bosnian", "Value": "Bosnian"},
    {"Label": "Botswanan", "Value": "Botswanan"},
    {"Label": "Brazilian", "Value": "Brazilian"},
    {"Label": "British", "Value": "British"},
    {"Label": "Bruneian", "Value": "Bruneian"},
    {"Label": "Bulgarian", "Value": "Bulgarian"},
    {"Label": "Burkinese", "Value": "Burkinese"},
    {"Label": "Burmese", "Value": "Burmese"},
    {"Label": "Burundian", "Value": "Burundian"},
    {"Label": "Cambodian", "Value": "Cambodian"},
    {"Label": "Cameroonian", "Value": "Cameroonian"},
    {"Label": "Canadian", "Value": "Canadian"},
    {"Label": "Cape Verdean", "Value": "Cape Verdean"},
    {"Label": "Chadian", "Value": "Chadian"},
    {"Label": "Chilean", "Value": "Chilean"},
    {"Label": "Chinese", "Value": "Chinese"},
    {"Label": "Colombian", "Value": "Colombian"},
    {"Label": "Congolese", "Value": "Congolese"},
    {"Label": "Costa Rican", "Value": "Costa Rican"},
    {"Label": "Croatian", "Value": "Croatian"},
    {"Label": "Cuban", "Value": "Cuban"},
    {"Label": "Cypriot", "Value": "Cypriot"},
    {"Label": "Czech", "Value": "Czech"},
    {"Label": "Danish", "Value": "Danish"},
    {"Label": "Djiboutian", "Value": "Djiboutian"},
    {"Label": "Dominican", "Value": "Dominican"},
    {"Label": "Dutch", "Value": "Dutch"},
    {"Label": "Ecuadorean", "Value": "Ecuadorean"},
    {"Label": "Egyptian", "Value": "Egyptian"},
    {"Label": "Emirati", "Value": "Emirati"},
    {"Label": "English", "Value": "English"},
    {"Label": "Eritrean", "Value": "Eritrean"},
    {"Label": "Estonian", "Value": "Estonian"},
    {"Label": "Ethiopian", "Value": "Ethiopian"},
    {"Label": "Fijian", "Value": "Fijian"},
    {"Label": "Finnish", "Value": "Finnish"},
    {"Label": "French", "Value": "French"},
    {"Label": "Gabonese", "Value": "Gabonese"},
    {"Label": "Gambian", "Value": "Gambian"},
    {"Label": "Georgian", "Value": "Georgian"},
    {"Label": "German", "Value": "German"},
    {"Label": "Ghanaian", "Value": "Ghanaian"},
    {"Label": "Greek", "Value": "Greek"},
    {"Label": "Grenadian", "Value": "Grenadian"},
    {"Label": "Guatemalan", "Value": "Guatemalan"},
    {"Label": "Guinean", "Value": "Guinean"},
    {"Label": "Guyanese", "Value": "Guyanese"},
    {"Label": "Haitian", "Value": "Haitian"},
    {"Label": "Honduran", "Value": "Honduran"},
    {"Label": "Hungarian", "Value": "Hungarian"},
    {"Label": "Icelandic", "Value": "Icelandic"},
    {"Label": "Indian", "Value": "Indian"},
    {"Label": "Indonesian", "Value": "Indonesian"},
    {"Label": "Iranian", "Value": "Iranian"},
    {"Label": "Iraqi", "Value": "Iraqi"},
    {"Label": "Irish", "Value": "Irish"},
    {"Label": "Italian", "Value": "Italian"},
    {"Label": "Jamaican", "Value": "Jamaican"},
    {"Label": "Japanese", "Value": "Japanese"},
    {"Label": "Jordanian", "Value": "Jordanian"},
    {"Label": "Kazakh", "Value": "Kazakh"},
    {"Label": "Kenyan", "Value": "Kenyan"},
    {"Label": "Kuwaiti", "Value": "Kuwaiti"},
    {"Label": "Laotian", "Value": "Laotian"},
    {"Label": "Latvian", "Value": "Latvian"},
    {"Label": "Lebanese", "Value": "Lebanese"},
    {"Label": "Liberian", "Value": "Liberian"},
    {"Label": "Libyan", "Value": "Libyan"},
    {"Label": "Lithuanian", "Value": "Lithuanian"},
    {"Label": "Macedonian", "Value": "Macedonian"},
    {"Label": "Madagascan", "Value": "Madagascan"},
    {"Label": "Malawian", "Value": "Malawian"},
    {"Label": "Malaysian", "Value": "Malaysian"},
    {"Label": "Maldivian", "Value": "Maldivian"},
    {"Label": "Malian", "Value": "Malian"},
    {"Label": "Maltese", "Value": "Maltese"},
    {"Label": "Mauritanian", "Value": "Mauritanian"},
    {"Label": "Mauritian", "Value": "Mauritian"},
    {"Label": "Mexican", "Value": "Mexican"},
    {"Label": "Moldovan", "Value": "Moldovan"},
    {"Label": "Monacan", "Value": "Monacan"},
    {"Label": "Mongolian", "Value": "Mongolian"},
    {"Label": "Montenegrin", "Value": "Montenegrin"},
    {"Label": "Moroccan", "Value": "Moroccan"},
    {"Label": "Mozambican", "Value": "Mozambican"},
    {"Label": "Namibian", "Value": "Namibian"},
    {"Label": "Nepalese", "Value": "Nepalese"},
    {"Label": "New Zealand", "Value": "New Zealand"},
    {"Label": "Nicaraguan", "Value": "Nicaraguan"},
    {"Label": "Nigerian", "Value": "Nigerian"},
    {"Label": "Nigerien", "Value": "Nigerien"},
    {"Label": "North Korean", "Value": "North Korean"},
    {"Label": "Norwegian", "Value": "Norwegian"},
    {"Label": "Omani", "Value": "Omani"},
    {"Label": "Pakistani", "Value": "Pakistani"},
    {"Label": "Palestinian", "Value": "Palestinian"},
    {"Label": "Panamanian", "Value": "Panamanian"},
    {"Label": "Papua New Guinean", "Value": "Papua New Guinean"},
    {"Label": "Paraguayan", "Value": "Paraguayan"},
    {"Label": "Peruvian", "Value": "Peruvian"},
    {"Label": "Philippine", "Value": "Philippine"},
    {"Label": "Polish", "Value": "Polish"},
    {"Label": "Portuguese", "Value": "Portuguese"},
    {"Label": "Qatari", "Value": "Qatari"},
    {"Label": "Romanian", "Value": "Romanian"},
    {"Label": "Russian", "Value": "Russian"},
    {"Label": "Rwandan", "Value": "Rwandan"},
    {"Label": "Salvadorean", "Value": "Salvadorean"},
    {"Label": "Saudi Arabian", "Value": "Saudi Arabian"},
    {"Label": "Scottish", "Value": "Scottish"},
    {"Label": "Senegalese", "Value": "Senegalese"},
    {"Label": "Serbian", "Value": "Serbian"},
    {"Label": "Seychellois", "Value": "Seychellois"},
    {"Label": "Sierra Leonian", "Value": "Sierra Leonian"},
    {"Label": "Singaporean", "Value": "Singaporean"},
    {"Label": "Slovak", "Value": "Slovak"},
    {"Label": "Slovenian", "Value": "Slovenian"},
    {"Label": "Somali", "Value": "Somali"},
    {"Label": "South African", "Value": "South African"},
    {"Label": "South Korean", "Value": "South Korean"},
    {"Label": "Spanish", "Value": "Spanish"},
    {"Label": "Sri Lankan", "Value": "Sri Lankan"},
    {"Label": "Sudanese", "Value": "Sudanese"},
    {"Label": "Surinamese", "Value": "Surinamese"},
    {"Label": "Swazi", "Value": "Swazi"},
    {"Label": "Swedish", "Value": "Swedish"},
    {"Label": "Swiss", "Value": "Swiss"},
    {"Label": "Syrian", "Value": "Syrian"},
    {"Label": "Taiwanese", "Value": "Taiwanese"},
    {"Label": "Tajik", "Value": "Tajik"},
    {"Label": "Tanzanian", "Value": "Tanzanian"},
    {"Label": "Thai", "Value": "Thai"},
    {"Label": "Togolese", "Value": "Togolese"},
    {"Label": "Trinidadian", "Value": "Trinidadian"},
    {"Label": "Tunisian", "Value": "Tunisian"},
    {"Label": "Turkish", "Value": "Turkish"},
    {"Label": "Turkmen", "Value": "Turkmen"},
    {"Label": "Tuvaluan", "Value": "Tuvaluan"},
    {"Label": "Ugandan", "Value": "Ugandan"},
    {"Label": "Ukrainian", "Value": "Ukrainian"},
    {"Label": "Uruguayan", "Value": "Uruguayan"},
    {"Label": "Uzbek", "Value": "Uzbek"},
    {"Label": "Vanuatuan", "Value": "Vanuatuan"},
    {"Label": "Venezuelan", "Value": "Venezuelan"},
    {"Label": "Vietnamese", "Value": "Vietnamese"},
    {"Label": "Welsh", "Value": "Welsh"},
    {"Label": "Western Samoan", "Value": "Western Samoan"},
    {"Label": "Yemeni", "Value": "Yemeni"},
    {"Label": "Yugoslav", "Value": "Yugoslav"},
    {"Label": "Zaïrean", "Value": "Zaïrean"},
    {"Label": "Zambian", "Value": "Zambian"},
    {"Label": "Zimbabwean", "Value": "Zimbabwean"},
    {"Label": "Ivory Coast", "Value": "Ivory Coast"}
  ]
  

  try {
    // Insert nationalities into the database
    await Nationality.insertMany(nationalities);
    res.status(200).send('Nationalities added successfully!');
  } catch (error) {
    res.status(500).send('Error adding nationalities: ' + error.message);
  }
};
exports.getNationalities = async (req, res) => {
    try {
      const nationalities = await Nationality.find();
      res.status(200).json(nationalities);
    } catch (error) {
      res.status(500).send('Error fetching nationalities: ' + error.message);
    }
  };
