module.exports = [
    { Label: "Accounting",                 Value: "Accounting" },
    { Label: "AML",                        Value: "AML" },
    { Label: "Ancillary Services",          Value: "Ancillary Services" },
    { Label: "Application Fee",             Value: "Application Fee" },
    { Label: "Approval",                    Value: "Approval" },
    { Label: "Attestation Fee",             Value: "Attestation Fee" },
    { Label: "Background Checks",           Value: "Background Checks" },
    { Label: "Bank Account Opening",        Value: "Bank Account Opening" },
    { Label: "Bank Charges",                Value: "Bank Charges" },
    { Label: "Business Center",             Value: "Business Center" },
    { Label: "BVI Offshore",                Value: "BVI Offshore" },
    { Label: "Commission",                  Value: "Commission" },
    { Label: "Compliance Services",         Value: "Compliance Services" },
    { Label: "Copyright",                   Value: "Copyright" },
    { Label: "Corporate Tax",               Value: "Corporate Tax" },
    { Label: "Courier Fee",                 Value: "Discounts" },
    { Label: "Creative City",               Value: "Discounts" },
    { Label: "DED",                         Value: "Discounts" },
    { Label: "Dependent Visas",             Value: "Discounts" },
    { Label: "DIC",                         Value: "Discounts" },
    { Label: "Directorships",               Value: "Discounts" },
    { Label: "Discounts",                   Value: "Discounts" },
    { Label: "DMCC",                        Value: "DMCC" },
    { Label: "Donation",                    Value: "Donation" },
    { Label: "Dubai Media City",            Value: "Dubai Media City" },
    { Label: "Dubai South",                 Value: "Dubai South" },
    { Label: "DWTC",                        Value: "DWTC" },
    { Label: "E-channel",                   Value: "E-channel" },
    { Label: "Finance Fees",                Value: "Finance Fees" },
    { Label: "Golden Visa",                 Value: "Golden Visa" },
    { Label: "Government Fee",              Value: "Government Fee" },
    { Label: "Government Fee 10%",          Value: "Government Fee 10%" },
    { Label: "Government Fee 90%",          Value: "Government Fee 90%" },
    { Label: "Health Insurance",            Value: "Health Insurance" },
    { Label: "HFZA",                        Value: "HFZA" },
    { Label: "IT Services",                 Value: "IT Services" },
    { Label: "JAFZA",                       Value: "JAFZA" },
    { Label: "Legal Services",              Value: "Legal Services" },
    { Label: "License Add-Ons",             Value: "License Add-Ons" },
    { Label: "License Deregistration",      Value: "License Deregistration" },
    { Label: "License New",                 Value: "License New" },
    { Label: "License Renewal",             Value: "License Renewal" },
    { Label: "Licenses",                    Value: "Licenses" },
    { Label: "Mail Management",             Value: "Mail Management" },
    { Label: "Miscellaneous",               Value: "Miscellaneous" },
    { Label: "Office Space",                Value: "Office Space" },
    { Label: "Other",                       Value: "Others" },
    { Label: "Other Government Fee",        Value: "Other Government Fee" },
    { Label: "Partnerships",                Value: "Partnerships" },
    { Label: "Passport",                    Value: "Passport" },
    { Label: "Passport Application Fee",    Value: "Passport Application Fee" },
    { Label: "Payroll",                     Value: "Payroll" },
    { Label: "Processing Fee",              Value: "Processing Fee" },
    { Label: "Professional Fees",           Value: "Professional Fees" },
    { Label: "PRO Services",                Value: "PRO Services" },
    { Label: "RAK Offshore",                Value: "RAK Offshore" },
    { Label: "Real Estate",                 Value: "Real Estate" },
    { Label: "Sales Targets",               Value: "Sales Targets" },
    { Label: "Security Deposits",           Value: "Security Deposits" },
    { Label: "SHAMS",                       Value: "SHAMS" },
    { Label: "Special Approvals",           Value: "Special Approvals" },
    { Label: "Sponsorships",                Value: "Sponsorships" },
    { Label: "Submission",                  Value: "Submission" },
    { Label: "Third Party Costs",           Value: "Third Party Costs" },
    { Label: "Tourist Visa",                Value: "Tourist Visa" },
    { Label: "Transguard Group",            Value: "Transguard Group" },
    { Label: "UAE",                         Value: "UAE" },
    { Label: "UAQ",                         Value: "UAQ" },
    { Label: "VAT & Tax Consultancy",       Value: "VAT & Tax Consultancy" },
    { Label: "VirtuACCOUNTS",               Value: "VirtuACCOUNTS" },
    { Label: "Virtual Receptionist",        Value: "Virtual Receptionist" },
    { Label: "Virtubundle",                 Value: "Virtubundle" },
    { Label: "Virtubundle-Basic",           Value: "Virtubundle-Basic" },
    { Label: "Virtubundle-Essential",       Value: "Virtubundle-Essential" },
    { Label: "Virtubundle-Premium",         Value: "Virtubundle-Premium" },
    { Label: "Virtubundle-Premium Plus",    Value: "Virtubundle-Premium Plus" },
    { Label: "VirtuDESIGN",                Value: "VirtuDESIGN" },
    { Label: "VirtuFit",                   Value: "VirtuFit" },
    { Label: "VirtuHealth",                Value: "VirtuHealth" },
    { Label: "VirtuLegal",                 Value: "VirtuLegal" },
    { Label: "VirtuLINK",                  Value: "VirtuLINK" },
    { Label: "VirtuMAIL",                  Value: "VirtuMAIL" },
    { Label: "VirtuPRO",                   Value: "VirtuPRO" },
    { Label: "VirtuTECH",                  Value: "VirtuTECH" },
    { Label: "Visa Add-Ons",               Value: "Visa Add-Ons" },
    { Label: "Visa New",                   Value: "Visa New" },
    { Label: "Visa Renewal",               Value: "Visa Renewal" },
    { Label: "Visas",                      Value: "Visas" },
  ];
  